#pragma once

#include <stdint.h>

// Auto-generated by web build endpoint. Do not edit manually.
#define UI_FONT_NAME "System Sans"
#define UI_THEME_DARK 0
#define UI_BUILD_ID "2026-03-16T23:25:24.333Z"
#define PARTIAL_REFRESH_MS_OVERRIDE 30000
#define FULL_REFRESH_EVERY_N_PARTIALS_OVERRIDE 60
#define WIFI_SSID_BUILD ""
#define WIFI_PASSWORD_BUILD ""
#define HOME_ASSISTANT_URL_BUILD "http://192.168.1.84:8123"
#define HOME_ASSISTANT_TOKEN_BUILD "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2MzdiMmNlNzVmNTg0Y2YxYTcyODcwNDhiY2E2MDJjNSIsImlhdCI6MTc3MzY2OTUyNiwiZXhwIjoyMDg5MDI5NTI2fQ.L7NvUNL8B06mKH5555KgO2g7wjgxSavc_EeC2vGxxLg"
#define HOME_ASSISTANT_ENABLED_BUILD 1

enum UiWidgetType : uint8_t {
  UI_WIDGET_CLOCK = 0,
  UI_WIDGET_WEATHER = 1,
  UI_WIDGET_PROGRESS = 2,
  UI_WIDGET_SWITCH = 3,
  UI_WIDGET_SLIDER = 4,
  UI_WIDGET_THERMOSTAT = 5,
  UI_WIDGET_NONE = 255,
};

enum UiClockStyle : uint8_t {
  UI_CLOCK_DIGITAL = 0,
  UI_CLOCK_ANALOG = 1,
};

enum UiPageType : uint8_t {
  UI_PAGE_STANDARD = 0,
  UI_PAGE_WEATHER_FOCUS = 1,
  UI_PAGE_MEDIA_PLAYER = 2,
};

typedef struct {
  uint8_t type;
  const char *label;
  const char *icon;
  int16_t value;
  int16_t currentValue;
  int16_t maxValue;
  uint8_t enabled;
  uint8_t clockStyle;
  uint8_t showSeconds;
  const char *entityId;
} UiWidgetConfig;

typedef struct {
  uint8_t pageType;
  const char *name;
  uint8_t widgetCount;
  const char *entityId;
  UiWidgetConfig widgets[5];
} UiPageConfig;

#define UI_PAGE_COUNT 3
#define UI_MAX_WIDGETS_PER_PAGE 5
static const UiPageConfig UI_PAGES[UI_PAGE_COUNT] = {
  {UI_PAGE_STANDARD, "Arbeitszimmer", 5, "", {{UI_WIDGET_CLOCK, "Clock", "", 0, 0, 100, 0, UI_CLOCK_DIGITAL, 1, ""}, {UI_WIDGET_WEATHER, "Berlin", "", 0, 0, 100, 0, UI_CLOCK_DIGITAL, 1, "weather.pirateweather"}, {UI_WIDGET_SWITCH, "Gästemodus", "", 0, 0, 100, 0, UI_CLOCK_DIGITAL, 1, "input_boolean.night_mode"}, {UI_WIDGET_SLIDER, "Arbeitszimmer", "lightbulb", 40, 0, 100, 0, UI_CLOCK_DIGITAL, 1, "light.arbeitszimmer"}, {UI_WIDGET_PROGRESS, "CoreOne", "", 40, 0, 100, 0, UI_CLOCK_DIGITAL, 1, "sensor.prusa_core_one_fortschritt"}}},
  {UI_PAGE_WEATHER_FOCUS, "Weather 3", 0, "weather.pirateweather", {{UI_WIDGET_NONE, "", "", 0, 0, 100, 0, UI_CLOCK_DIGITAL, 1, ""}, {UI_WIDGET_NONE, "", "", 0, 0, 100, 0, UI_CLOCK_DIGITAL, 1, ""}, {UI_WIDGET_NONE, "", "", 0, 0, 100, 0, UI_CLOCK_DIGITAL, 1, ""}, {UI_WIDGET_NONE, "", "", 0, 0, 100, 0, UI_CLOCK_DIGITAL, 1, ""}, {UI_WIDGET_NONE, "", "", 0, 0, 100, 0, UI_CLOCK_DIGITAL, 1, ""}}},
  {UI_PAGE_MEDIA_PLAYER, "Player 3", 0, "media_player.spotify", {{UI_WIDGET_NONE, "", "", 0, 0, 100, 0, UI_CLOCK_DIGITAL, 1, ""}, {UI_WIDGET_NONE, "", "", 0, 0, 100, 0, UI_CLOCK_DIGITAL, 1, ""}, {UI_WIDGET_NONE, "", "", 0, 0, 100, 0, UI_CLOCK_DIGITAL, 1, ""}, {UI_WIDGET_NONE, "", "", 0, 0, 100, 0, UI_CLOCK_DIGITAL, 1, ""}, {UI_WIDGET_NONE, "", "", 0, 0, 100, 0, UI_CLOCK_DIGITAL, 1, ""}}}
};
