#pragma once

#include <stdint.h>

// Auto-generated by web build endpoint. Do not edit manually.
#define UI_FONT_NAME "Mono"
#define UI_THEME_DARK 0
#define UI_BUILD_ID "2026-03-13T14:20:11.610Z"
#define PARTIAL_REFRESH_MS_OVERRIDE 30000
#define FULL_REFRESH_EVERY_N_PARTIALS_OVERRIDE 60
#define WIFI_SSID_BUILD ""
#define WIFI_PASSWORD_BUILD ""

enum UiWidgetType : uint8_t {
  UI_WIDGET_CLOCK = 0,
  UI_WIDGET_WEATHER = 1,
  UI_WIDGET_PROGRESS = 2,
  UI_WIDGET_SWITCH = 3,
  UI_WIDGET_SLIDER = 4,
  UI_WIDGET_THERMOSTAT = 5,
  UI_WIDGET_NONE = 255,
};

enum UiClockStyle : uint8_t {
  UI_CLOCK_DIGITAL = 0,
  UI_CLOCK_ANALOG = 1,
};

enum UiPageType : uint8_t {
  UI_PAGE_STANDARD = 0,
  UI_PAGE_WEATHER_FOCUS = 1,
};

typedef struct {
  uint8_t type;
  const char *label;
  int16_t value;
  int16_t currentValue;
  int16_t maxValue;
  uint8_t enabled;
  uint8_t clockStyle;
  uint8_t showSeconds;
} UiWidgetConfig;

typedef struct {
  uint8_t pageType;
  const char *name;
  uint8_t widgetCount;
  UiWidgetConfig widgets[4];
} UiPageConfig;

#define UI_PAGE_COUNT 2
#define UI_MAX_WIDGETS_PER_PAGE 4
static const UiPageConfig UI_PAGES[UI_PAGE_COUNT] = {
  {UI_PAGE_STANDARD, "Home", 2, {{UI_WIDGET_PROGRESS, "Progress", 45, 0, 100, 0, UI_CLOCK_DIGITAL, 1}, {UI_WIDGET_THERMOSTAT, "Thermostat", 220, 200, 300, 0, UI_CLOCK_DIGITAL, 1}, {UI_WIDGET_NONE, "", 0, 0, 100, 0, UI_CLOCK_DIGITAL, 1}, {UI_WIDGET_NONE, "", 0, 0, 100, 0, UI_CLOCK_DIGITAL, 1}}},
  {UI_PAGE_STANDARD, "Page 2", 4, {{UI_WIDGET_CLOCK, "Clock", 0, 0, 100, 0, UI_CLOCK_DIGITAL, 1}, {UI_WIDGET_WEATHER, "Weather", 0, 0, 100, 0, UI_CLOCK_DIGITAL, 1}, {UI_WIDGET_PROGRESS, "Progress", 40, 0, 100, 0, UI_CLOCK_DIGITAL, 1}, {UI_WIDGET_SWITCH, "Switch", 0, 0, 100, 0, UI_CLOCK_DIGITAL, 1}}}
};
