from pathlib import Path
import os

Import("env")


def parse_dotenv(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        values[key] = value

    return values


def c_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


project_dir = Path(env.subst("$PROJECT_DIR"))
dotenv_values = parse_dotenv(project_dir / ".env")

ssid = os.getenv("FIRMWARE_WIFI_SSID", "").strip() or dotenv_values.get("WIFI_SSID", "").strip()
password = os.getenv("FIRMWARE_WIFI_PASSWORD", "").strip() or dotenv_values.get("WIFI_PASSWORD", "").strip()

header_path = project_dir / "include" / "generated_pio_wifi.h"
header_path.write_text(
    "\n".join(
        [
            "#pragma once",
            "",
            "// Auto-generated by tools/load_env.py for local PlatformIO builds.",
            f'#define WIFI_SSID_PIO "{c_escape(ssid)}"',
            f'#define WIFI_PASSWORD_PIO "{c_escape(password)}"',
            "",
        ]
    ),
    encoding="utf-8",
)

if ssid:
    print("[load_env] Added local Wi-Fi credentials for PlatformIO build.")
else:
    print("[load_env] No local Wi-Fi credentials found in env/.env.")
